# Generated by Django 4.2.7 on 2023-11-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('phone', models.IntegerField(max_length=20)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
