# Generated by Django 4.2.7 on 2023-11-14 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='phone',
        ),
    ]
