# Generated by Django 4.2.7 on 2023-11-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_trainee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='phone',
            field=models.IntegerField(default=None),
        ),
    ]
