# Generated by Django 4.2.7 on 2023-11-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_remove_trainee_message_trainee_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='password',
            field=models.CharField(default='new', max_length=100),
        ),
    ]
