# Generated by Django 4.2.7 on 2023-11-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_trainee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
