# Generated by Django 4.2.7 on 2023-11-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_trainee_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='password',
        ),
    ]
