# Generated by Django 4.2.7 on 2023-11-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_remove_trainee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
