# Generated by Django 4.2.7 on 2023-11-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_remove_trainee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
