# Generated by Django 4.2.7 on 2023-11-16 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_trainee_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainee',
            old_name='password',
            new_name='message',
        ),
    ]
